import os
import time
import argparse
import torch
import pandas as pd
from torch.autograd import Variable
from HyperTools import *
from Model_S3ANet import *
from Metrics import compute_sam, compute_sid, compute_physical_consistency, compute_asr

DataName = {1: 'PaviaU', 2: 'Salinas', 3: 'Houston', 4: 'IndianP'}

def main(args):
    results = []
    
    for data_id in range(1, 5):
        try:
            print(f"\\n{'='*50}")
            print(f"Running Attack on {DataName[data_id]}")
            print(f"{'='*50}\\n")
            
            if data_id == 1:
                num_classes = 9
                num_features = 103
                save_pre_dir = './Data/PaviaU/'
            elif data_id == 2:
                num_classes = 16
                num_features = 204
                save_pre_dir = './Data/Salinas/'
            elif data_id == 3:
                num_classes = 7  # Houston reverted to 7-classes based on provided data
                num_features = 144
                save_pre_dir = './Data/Houston/'
            elif data_id == 4:
                num_classes = 16
                num_features = 200
                save_pre_dir = './Data/IndianP/'
                
            # If dataset hasn't been generated by GenSample, we skip or generate it.
            # Assuming GenSample has been run prior.
            if not os.path.exists(save_pre_dir + 'X.npy'):
                print(f"Dataset {DataName[data_id]} not prepared. Please run GenSample.py first.")
                continue
                
            X = np.load(save_pre_dir + 'X.npy')
            _, h, w = X.shape
            Y = np.load(save_pre_dir + 'Y.npy')

            X_train = np.reshape(X, (1, num_features, h, w))
            train_array = np.load(save_pre_dir + 'train_array.npy')
            test_array = np.load(save_pre_dir + 'test_array.npy')
            Y_train = np.ones(Y.shape) * 255
            Y_train[train_array] = Y[train_array]
            Y_train = np.reshape(Y_train, (1, h, w))

            Y_tar = np.zeros(Y.shape)
            Y_tar = np.reshape(Y_tar, (1, h, w))

            Model = S3ANet(num_features=num_features, num_classes=num_classes, bins=args.bins).cuda()
            Model.train()
            optimizer = torch.optim.Adam(Model.parameters(), lr=args.lr, weight_decay=args.decay)
            criterion = CrossEntropy2d().cuda()

            images = torch.from_numpy(X_train).float().cuda()
            label = torch.from_numpy(Y_train).long().cuda()

            # Train for args.epoch epochs
            for epoch in range(args.epoch):
                adjust_learning_rate(optimizer, args.lr, epoch, args.epoch)
                optimizer.zero_grad()
                output = Model(images)
                seg_loss = criterion(output, label)
                seg_loss.backward()
                optimizer.step()

            Model.eval()
            
            # Clean predictions
            clean_output = Model(images)
            _, clean_predict_labels = torch.max(clean_output, 1)
            clean_predict_labels = np.squeeze(clean_predict_labels.detach().cpu().numpy()).reshape(-1)

            # Adversarial Attack (FGSM)
            processed_image = Variable(images)
            processed_image = processed_image.requires_grad_()
            label_tar = torch.from_numpy(Y_tar).long().cuda()

            output = Model(processed_image)
            seg_loss = criterion(output, label_tar)
            seg_loss.backward()
            
            adv_noise = args.epsilon * processed_image.grad.data / torch.norm(processed_image.grad.data, float("inf"))
            processed_image.data = processed_image.data - adv_noise
            
            X_adv_tensor = torch.clamp(processed_image, 0, 1)
            X_adv = X_adv_tensor.cpu().data.numpy()[0]
            X_adv = np.reshape(X_adv, (1, num_features, h, w))
            
            adv_images = torch.from_numpy(X_adv).float().cuda()

            # Adversarial predictions
            output = Model(adv_images)
            _, predict_labels = torch.max(output, 1)
            predict_labels = np.squeeze(predict_labels.detach().cpu().numpy()).reshape(-1)

            # --- Calculate Standard Metrics ---
            OA2, kappa2, ProducerA2 = CalAccuracy(predict_labels[test_array], Y[test_array])
            AA2 = np.mean(ProducerA2)

            # --- Calculate Advanced Metrics ---
            # Reshape inputs for metric calculation: (N, C)
            X_flat_clean = X_train.reshape(num_features, -1).T
            X_flat_adv = X_adv.reshape(num_features, -1).T
            
            # Use only test pixels for metrics
            X_clean_test = X_flat_clean[test_array]
            X_adv_test = X_flat_adv[test_array]
            
            sam_val = compute_sam(X_clean_test, X_adv_test)
            sid_val = compute_sid(X_clean_test, X_adv_test)
            asr_val = compute_asr(clean_predict_labels, predict_labels, Y.reshape(-1), test_array)
            
            # For physical consistency, we run VCA + FCLS. 
            # We use a subset of test pixels to speed up unmixing.
            phys_cons = compute_physical_consistency(X_clean_test[:1000], X_adv_test[:1000], theta=0.1)

            print(f"Results for {DataName[data_id]}:")
            print(f"OA: {OA2*100:.2f}%, Kappa: {kappa2:.4f}, AA: {AA2*100:.2f}%")
            print(f"SAM: {sam_val:.4f} rad, SID: {sid_val:.4f}")
            print(f"ASR: {asr_val*100:.2f}%, Phys. Consistency: {phys_cons*100:.2f}%")
            
            # Save to list
            results.append({
                'Dataset': DataName[data_id],
                'OA (%)': OA2 * 100,
                'Kappa': kappa2,
                'AA (%)': AA2 * 100,
                'SAM (rad)': sam_val,
                'SID': sid_val,
                'ASR (%)': asr_val * 100,
                'Physical Consistency (%)': phys_cons * 100
            })
            
        except Exception as e:
            print(f"Failed to process {DataName[data_id]}: {str(e)}")

    if len(results) > 0:
        df = pd.DataFrame(results)
        df.to_excel('FGSM_Advanced_Metrics_Results.xlsx', index=False)
        print("\\nAll results successfully saved to 'FGSM_Advanced_Metrics_Results.xlsx'!")
    else:
        print("\\nNo results were generated.")


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--lr', type=float, default=5e-4)
    parser.add_argument('--decay', type=float, default=5e-5)
    parser.add_argument('--epsilon', type=float, default=0.04)
    parser.add_argument('--epoch', type=int, default=500) # Fast default for testing
    parser.add_argument('--bins', nargs='+', type=int)

    args = parser.parse_args()
    main(args)
