"""
Test_Perturbed_S3ANet.py
========================
Run a clean S3ANet model on FGSM-perturbed (adversarial) hyperspectral data
and store ALL evaluation metrics in an Excel report.

Workflow
--------
1. Load pre-processed data (.npy files generated by GenSample.py)
2. Train S3ANet on clean data
3. Capture clean predictions (needed for ASR)
4. Generate FGSM adversarial example
5. Evaluate the unmodified (clean) model on the adversarial image
6. Compute all metrics:
      Classification : OA, Kappa, AA, per-class ProducerA
      Spectral       : SAM, SID
      Physical       : Physical-consistency rate (unmixing round-trip, theta=5 deg)
      Attack quality : ASR (attack success rate)
7. Save results to Excel  (<save_path_prefix>/Perturbed_Results.xlsx)

Usage
-----
  # Single dataset
  python Test_Perturbed_S3ANet.py --dataID 1 --epsilon 0.04 --epoch 1000

  # All four datasets in one run
  python Test_Perturbed_S3ANet.py --dataID 0 --epsilon 0.04 --epoch 1000
"""

import os
import time
import argparse
import random

import numpy as np
import pandas as pd
import torch
from torch.autograd import Variable

from HyperTools import *       # CalAccuracy, CalSAM, CalSID, CalPhysicalConsistency, CalASR,
                               # DrawResult, adjust_learning_rate, CrossEntropy2d
from Model_S3ANet import *     # S3ANet

# ─────────────────────────────────────────────────────────────────────────────
# Dataset registry
# ─────────────────────────────────────────────────────────────────────────────
DataName = {
    1: 'PaviaU',
    2: 'Salinas',
    3: 'Houston',
    4: 'IndianP',
}

DATASET_CFG = {
    1: dict(num_classes=9,  num_features=103, save_pre_dir='./Data/PaviaU/'),
    2: dict(num_classes=16, num_features=204, save_pre_dir='./Data/Salinas/'),
    3: dict(num_classes=15, num_features=144, save_pre_dir='./Data/Houston/'),
    4: dict(num_classes=16, num_features=200, save_pre_dir='./Data/IndianP/'),
}

# ─────────────────────────────────────────────────────────────────────────────
# Reproducibility
# ─────────────────────────────────────────────────────────────────────────────
def set_seed(seed: int = 42):
    """Fix all random seeds for full reproducibility."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


# ─────────────────────────────────────────────────────────────────────────────
# Per-dataset evaluation
# ─────────────────────────────────────────────────────────────────────────────
def run_one(args) -> dict:
    """
    Train S3ANet, attack the data, evaluate the clean model on adversarial
    data, and return a dict of all metrics.
    """
    set_seed(42)

    dataset_name = DataName[args.dataID]
    cfg          = DATASET_CFG[args.dataID]
    save_pre_dir = cfg['save_pre_dir']

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f'\nUsing device: {device}')

    # ── Load data ─────────────────────────────────────────────────────────────
    X            = np.load(save_pre_dir + 'X.npy')          # (C, H, W)
    num_features, h, w = X.shape
    Y            = np.load(save_pre_dir + 'Y.npy')          # (H*W,)
    num_classes  = int(Y.max()) + 1

    train_array  = np.load(save_pre_dir + 'train_array.npy')
    test_array   = np.load(save_pre_dir + 'test_array.npy')

    # Training label map (unlabelled → 255)
    Y_train = np.ones(Y.shape) * 255
    Y_train[train_array] = Y[train_array]
    Y_train = np.reshape(Y_train, (1, h, w))                # (1, H, W)

    # NOTE: Y_tar kept for reference but untargeted FGSM is used below
    Y_tar = np.zeros(Y.shape, dtype=np.int64)
    Y_tar = np.reshape(Y_tar, (1, h, w))

    # 5-D input tensor [batch=1, depth=1, C, H, W] → collapse to 4-D for Conv2d
    X_5d       = np.reshape(X, (1, 1, num_features, h, w))
    images_5d  = torch.from_numpy(X_5d).float().to(device)
    b, d, c, h_dim, w_dim = images_5d.shape
    images     = images_5d.view(b * d, c, h_dim, w_dim)     # (1, C, H, W)

    label      = torch.from_numpy(Y_train).long().to(device)
    label_tar  = torch.from_numpy(Y_tar).long().to(device)
    criterion  = CrossEntropy2d().to(device)

    # ── Output directory ──────────────────────────────────────────────────────
    save_path_prefix = os.path.join(
        args.save_path_prefix,
        'Exp_Perturbed_' + dataset_name + '/'
    )
    os.makedirs(save_path_prefix, exist_ok=True)

    # ── Build model ───────────────────────────────────────────────────────────
    Model = S3ANet(
        num_features=num_features,
        num_classes=num_classes,
        bins=args.bins,
    ).to(device)

    optimizer = torch.optim.Adam(
        Model.parameters(), lr=args.lr, weight_decay=args.decay
    )

    # ── Training ──────────────────────────────────────────────────────────────
    num_epochs  = args.epoch
    print(f'=== Training S3ANet on {dataset_name} for {num_epochs} epochs ===')
    Model.train()
    tr_start = time.time()

    for epoch in range(num_epochs):
        adjust_learning_rate(optimizer, args.lr, epoch, num_epochs)
        optimizer.zero_grad()
        output   = Model(images)
        seg_loss = criterion(output, label)
        seg_loss.backward()
        optimizer.step()
        if (epoch + 1) % 50 == 0 or epoch == 0:
            print('  epoch %d/%d  cls_loss = %.4f' % (epoch + 1, num_epochs, seg_loss.item()))

    train_time = time.time() - tr_start
    print(f'Training finished in {train_time:.2f}s')

    # ── Clean predictions (baseline, needed for ASR) ──────────────────────────
    Model.eval()
    with torch.no_grad():
        clean_out = Model(images)
    _, clean_lbl    = torch.max(clean_out, 1)
    clean_pred      = np.squeeze(clean_lbl.cpu().numpy()).reshape(-1)

    OA_clean, kappa_clean, ProducerA_clean = CalAccuracy(
        clean_pred[test_array], Y[test_array]
    )
    AA_clean = np.mean(ProducerA_clean)
    print(f'  [Clean]  OA={OA_clean*100:.3f}%  Kappa={kappa_clean*100:.3f}%  AA={AA_clean*100:.3f}%')

    # Keep numpy array for spectral metrics
    X_orig_np = images.cpu().data.numpy()[0]                 # (C, H, W)

    # ── FGSM adversarial attack (untargeted) ─────────────────────────────────
    # Standard FGSM: x_adv = x + ε * sign(∇_x L(x, y_true))
    # Using sign() ensures EVERY pixel/channel receives the full ε perturbation.
    # Dividing by L∞-norm (old code) left most pixels nearly unperturbed.
    print(f'Generating FGSM adversarial example (ε={args.epsilon})...')
    te_start = time.time()

    processed_image = Variable(images.clone()).requires_grad_(True)
    out_atk  = Model(processed_image)
    # Untargeted attack: maximise loss on TRUE labels → accuracy drops sharply
    loss_atk = criterion(out_atk, label)
    loss_atk.backward()

    # Standard FGSM sign step (adds noise in gradient direction to increase loss)
    adv_noise = args.epsilon * processed_image.grad.data.sign()
    processed_image.data = processed_image.data + adv_noise

    # Clamp to [0, 1] and recover numpy (C, H, W)
    X_adv_np = torch.clamp(processed_image, 0, 1).detach().cpu().numpy()[0]

    # ── Save adversarial image ────────────────────────────────────────────────
    adv_npy_path = os.path.join(
        save_path_prefix,
        f'S3ANet_FGSM_Xadv_eps{args.epsilon}.npy'
    )
    np.save(adv_npy_path, X_adv_np)
    print(f'  Adversarial data saved -> {adv_npy_path}')

    # ── Evaluate clean model on adversarial image ─────────────────────────────
    X_adv_5d  = np.reshape(X_adv_np, (1, 1, num_features, h, w))
    adv_5d    = torch.from_numpy(X_adv_5d).float().to(device)
    b2, d2, c2, h2, w2 = adv_5d.shape
    adv_images = adv_5d.view(b2 * d2, c2, h2, w2)

    with torch.no_grad():
        out_adv = Model(adv_images)
    _, adv_lbl     = torch.max(out_adv, 1)
    adv_pred       = np.squeeze(adv_lbl.cpu().numpy()).reshape(-1)

    test_time = time.time() - te_start

    OA_adv, kappa_adv, ProducerA_adv = CalAccuracy(
        adv_pred[test_array], Y[test_array]
    )
    AA_adv = np.mean(ProducerA_adv)
    print(f'  [Adv]    OA={OA_adv*100:.3f}%  Kappa={kappa_adv*100:.3f}%  AA={AA_adv*100:.3f}%')

    # ── Save adversarial classification map ───────────────────────────────────
    img_adv  = DrawResult(np.reshape(adv_pred + 1, -1), args.dataID, h, w)
    adv_map_path = os.path.join(
        save_path_prefix,
        f'S3ANet_FGSM_OA{int(OA_adv*10000)}_kappa{int(kappa_adv*10000)}_eps{args.epsilon}.png'
    )
    plt.imsave(adv_map_path, img_adv)
    print(f'  Adversarial map saved -> {adv_map_path}')

    # ── Spectral & physical metrics ───────────────────────────────────────────
    print('Computing SAM ...')
    sam_val   = CalSAM(X_orig_np, X_adv_np)

    print('Computing SID ...')
    sid_val   = CalSID(X_orig_np, X_adv_np)

    print('Computing physical-consistency rate (may take a moment)...')
    phys_rate = CalPhysicalConsistency(X_orig_np, X_adv_np, theta=args.theta)

    asr_val   = CalASR(clean_pred, adv_pred, Y, test_array)

    # ── Console summary ───────────────────────────────────────────────────────
    sep = '─' * 60
    print(sep)
    print(f'Dataset : {dataset_name}   |  ε = {args.epsilon}')
    print(sep)
    print('── Classification (clean model on CLEAN data) ──────────')
    print(f'  OA        : {OA_clean    * 100:.3f} %')
    print(f'  Kappa     : {kappa_clean * 100:.3f} %')
    print(f'  AA        : {AA_clean    * 100:.3f} %')
    print('── Classification (clean model on PERTURBED data) ──────')
    print(f'  OA        : {OA_adv    * 100:.3f} %')
    print(f'  Kappa     : {kappa_adv * 100:.3f} %')
    print(f'  AA        : {AA_adv    * 100:.3f} %')
    print('── Spectral / Physical Attack Metrics ──────────────────')
    print(f'  SAM  (mean spectral angle, deg)  : {sam_val:.4f}')
    print(f'  SID  (spectral info divergence)  : {sid_val:.6f}')
    print(f'  Physical-consistency rate (θ={args.theta}°) : {phys_rate:.4f}  ({phys_rate*100:.2f}%)')
    print(f'  ASR  (attack success rate)        : {asr_val:.4f}  ({asr_val*100:.2f}%)')
    print(f'  Train time : {train_time:.2f}s')
    print(f'  Attack+test time : {test_time:.2f}s')
    print(sep)

    # Build per-class producer accuracy strings
    pa_clean_str = '  |  '.join(
        f'C{i}={v*100:.2f}%' for i, v in enumerate(ProducerA_clean)
    )
    pa_adv_str = '  |  '.join(
        f'C{i}={v*100:.2f}%' for i, v in enumerate(ProducerA_adv)
    )

    return {
        'Dataset':                          dataset_name,
        'Epsilon':                          args.epsilon,
        # ── Clean baseline ──────────────────────────────────────────────
        'Clean OA (%)':                     round(OA_clean    * 100, 4),
        'Clean Kappa (%)':                  round(kappa_clean * 100, 4),
        'Clean AA (%)':                     round(AA_clean    * 100, 4),
        'Clean ProducerA (per class)':      pa_clean_str,
        # ── After perturbation ──────────────────────────────────────────
        'Perturbed OA (%)':                 round(OA_adv    * 100, 4),
        'Perturbed Kappa (%)':              round(kappa_adv * 100, 4),
        'Perturbed AA (%)':                 round(AA_adv    * 100, 4),
        'Perturbed ProducerA (per class)':  pa_adv_str,
        # ── Spectral / physical metrics ─────────────────────────────────
        'SAM (deg)':                        round(sam_val,   6),
        'SID':                              round(sid_val,   8),
        f'Physical Consistency Rate (θ={args.theta}°)': round(phys_rate, 6),
        'ASR':                              round(asr_val,   6),
        # ── Timing ─────────────────────────────────────────────────────
        'Train Time (s)':                   round(train_time, 2),
        'Attack+Test Time (s)':             round(test_time,  2),
        'Total Runtime (s)':                round(train_time + test_time, 2),
        # ── Paths ───────────────────────────────────────────────────────
        'Adversarial .npy':                 adv_npy_path,
        'Adversarial map (.png)':           adv_map_path,
    }


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────
def main(args):
    # Decide which datasets to run
    if args.dataID == 0:
        data_ids = list(DataName.keys())   # all four
    else:
        data_ids = [args.dataID]

    all_results = []

    for did in data_ids:
        print(f'\n{"="*65}')
        print(f'=== Dataset {did}: {DataName[did]} ===')
        print(f'{"="*65}')
        args.dataID = did
        row = run_one(args)
        all_results.append(row)

    # ── Save to Excel ─────────────────────────────────────────────────────────
    df = pd.DataFrame(all_results)

    os.makedirs(args.save_path_prefix, exist_ok=True)
    excel_path = os.path.join(
        args.save_path_prefix,
        f'Perturbed_Results_eps{args.epsilon}.xlsx'
    )
    df.to_excel(excel_path, index=False)
    print(f'\n✓ All results saved to Excel -> {excel_path}')
    print(df.to_string(index=False))

    return df


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Evaluate clean S3ANet on FGSM-perturbed HSI data; save metrics to Excel.'
    )
    parser.add_argument(
        '--dataID', type=int, default=0,
        help='Dataset ID: 0=all, 1=PaviaU, 2=Salinas, 3=Houston, 4=IndianP'
    )
    parser.add_argument('--save_path_prefix', type=str, default='./')
    parser.add_argument('--lr',      type=float, default=5e-4)
    parser.add_argument('--decay',   type=float, default=5e-5)
    parser.add_argument('--epsilon', type=float, default=0.04,
                        help='FGSM perturbation strength')
    parser.add_argument('--epoch',   type=int,   default=1000)
    parser.add_argument('--theta',   type=float, default=5.0,
                        help='SAM threshold for physical-consistency rate (degrees)')
    parser.add_argument('--bins', nargs='+', type=int, default=[1, 2, 3, 6])

    args = parser.parse_args()
    main(args)
